### PR TITLE
Add non-Go Windows packages

### PR DESCRIPTION
**Pull request by lidavidm**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by WillAyd** [comment]
Assuming we need to be passing `/WX` to MSVC instead of `/Werror`; surprised CMake doesn't already handle this for us

**Comment by lidavidm** [comment]
So that is actually due to Go. Go is invoking cl for us and it's translating our flags like Werror into /Werror automagically. I remember running into this before and I think it's easiest to force Go to invoke mingw-gcc

I realized when I got here that I've done half of this before:
https://github.com/apache/arrow-adbc/issues/634

So I think the next step here is to add a patch to GoUtils.cmake to set CC/CXX only for Go, and add mingw-gcc to the deps on windows. The issue there notes that the tests won't build/link, but that's OK for our purposes here.

**Comment by WillAyd** [comment]
Very interesting. Definitely not a conda thing either right? I've always found the environment variables set by activation of a conda environment to be surprising...not something I looked into here just food for thought

**Comment by lidavidm** [comment]
I don't think it's Conda-specific, I think we just don't do enough testing on Windows due to my own antipathy/lack of a Windows machine

**Comment by lidavidm** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
